services:
  agent_kwnowledge:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "8140:8000"
    volumes:
      - .:/app

    networks:
    - cluster

networks:
  cluster:
    external: true
